cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_1 && echo 1 | ./4_Sources_1
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_2 && echo 2 | ./4_Sources_2
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_3 && echo 3 | ./4_Sources_3
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_4 && echo 4 | ./4_Sources_4
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_5 && echo 5 | ./4_Sources_5
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_6 && echo 6 | ./4_Sources_6
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_7 && echo 7 | ./4_Sources_7
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_8 && echo 8 | ./4_Sources_8
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_9 && echo 9 | ./4_Sources_9
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_10 && echo 10 | ./4_Sources_10
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_11 && echo 11 | ./4_Sources_11
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_12 && echo 12 | ./4_Sources_12
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_13 && echo 13 | ./4_Sources_13
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_14 && echo 14 | ./4_Sources_14
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_15 && echo 15 | ./4_Sources_15
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_16 && echo 16 | ./4_Sources_16
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_17 && echo 17 | ./4_Sources_17
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_18 && echo 18 | ./4_Sources_18
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_19 && echo 19 | ./4_Sources_19
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_20 && echo 20 | ./4_Sources_20
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_21 && echo 21 | ./4_Sources_21
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_22 && echo 22 | ./4_Sources_22
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_23 && echo 23 | ./4_Sources_23
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_24 && echo 24 | ./4_Sources_24
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_25 && echo 25 | ./4_Sources_25
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_26 && echo 26 | ./4_Sources_26
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_27 && echo 27 | ./4_Sources_27
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_28 && echo 28 | ./4_Sources_28
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_29 && echo 29 | ./4_Sources_29
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_30 && echo 30 | ./4_Sources_30
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_31 && echo 31 | ./4_Sources_31
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_32 && echo 32 | ./4_Sources_32
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_33 && echo 33 | ./4_Sources_33
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_34 && echo 34 | ./4_Sources_34
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_35 && echo 35 | ./4_Sources_35
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_36 && echo 36 | ./4_Sources_36
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_37 && echo 37 | ./4_Sources_37
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_38 && echo 38 | ./4_Sources_38
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_39 && echo 39 | ./4_Sources_39
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_40 && echo 40 | ./4_Sources_40
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_41 && echo 41 | ./4_Sources_41
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_42 && echo 42 | ./4_Sources_42
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_43 && echo 43 | ./4_Sources_43
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_44 && echo 44 | ./4_Sources_44
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_45 && echo 45 | ./4_Sources_45
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_46 && echo 46 | ./4_Sources_46
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_47 && echo 47 | ./4_Sources_47
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_48 && echo 48 | ./4_Sources_48
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_49 && echo 49 | ./4_Sources_49
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_50 && echo 50 | ./4_Sources_50
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_51 && echo 51 | ./4_Sources_51
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_52 && echo 52 | ./4_Sources_52
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_53 && echo 53 | ./4_Sources_53
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_54 && echo 54 | ./4_Sources_54
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_55 && echo 55 | ./4_Sources_55
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_56 && echo 56 | ./4_Sources_56
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_57 && echo 57 | ./4_Sources_57
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_58 && echo 58 | ./4_Sources_58
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_59 && echo 59 | ./4_Sources_59
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_60 && echo 60 | ./4_Sources_60
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_61 && echo 61 | ./4_Sources_61
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_62 && echo 62 | ./4_Sources_62
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_63 && echo 63 | ./4_Sources_63
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_64 && echo 64 | ./4_Sources_64
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_65 && echo 65 | ./4_Sources_65
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_66 && echo 66 | ./4_Sources_66
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_67 && echo 67 | ./4_Sources_67
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_68 && echo 68 | ./4_Sources_68
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_69 && echo 69 | ./4_Sources_69
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_70 && echo 70 | ./4_Sources_70
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_71 && echo 71 | ./4_Sources_71
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_72 && echo 72 | ./4_Sources_72
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_73 && echo 73 | ./4_Sources_73
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_74 && echo 74 | ./4_Sources_74
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_75 && echo 75 | ./4_Sources_75
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_76 && echo 76 | ./4_Sources_76
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_77 && echo 77 | ./4_Sources_77
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_78 && echo 78 | ./4_Sources_78
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_79 && echo 79 | ./4_Sources_79
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_80 && echo 80 | ./4_Sources_80
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_81 && echo 81 | ./4_Sources_81
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_82 && echo 82 | ./4_Sources_82
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_83 && echo 83 | ./4_Sources_83
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_84 && echo 84 | ./4_Sources_84
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_85 && echo 85 | ./4_Sources_85
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_86 && echo 86 | ./4_Sources_86
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_87 && echo 87 | ./4_Sources_87
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_88 && echo 88 | ./4_Sources_88
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_89 && echo 89 | ./4_Sources_89
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_90 && echo 90 | ./4_Sources_90
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_91 && echo 91 | ./4_Sources_91
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_92 && echo 92 | ./4_Sources_92
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_93 && echo 93 | ./4_Sources_93
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_94 && echo 94 | ./4_Sources_94
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_95 && echo 95 | ./4_Sources_95
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_96 && echo 96 | ./4_Sources_96
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_97 && echo 97 | ./4_Sources_97
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_98 && echo 98 | ./4_Sources_98
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_99 && echo 99 | ./4_Sources_99
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_100 && echo 100 | ./4_Sources_100
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_101 && echo 101 | ./4_Sources_101
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_102 && echo 102 | ./4_Sources_102
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_103 && echo 103 | ./4_Sources_103
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_104 && echo 104 | ./4_Sources_104
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_105 && echo 105 | ./4_Sources_105
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_106 && echo 106 | ./4_Sources_106
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_107 && echo 107 | ./4_Sources_107
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_108 && echo 108 | ./4_Sources_108
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_109 && echo 109 | ./4_Sources_109
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_110 && echo 110 | ./4_Sources_110
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_111 && echo 111 | ./4_Sources_111
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_112 && echo 112 | ./4_Sources_112
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_113 && echo 113 | ./4_Sources_113
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_114 && echo 114 | ./4_Sources_114
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_115 && echo 115 | ./4_Sources_115
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_116 && echo 116 | ./4_Sources_116
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_117 && echo 117 | ./4_Sources_117
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_118 && echo 118 | ./4_Sources_118
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_119 && echo 119 | ./4_Sources_119
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_120 && echo 120 | ./4_Sources_120
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_121 && echo 121 | ./4_Sources_121
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_122 && echo 122 | ./4_Sources_122
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_123 && echo 123 | ./4_Sources_123
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_124 && echo 124 | ./4_Sources_124
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_125 && echo 125 | ./4_Sources_125
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_126 && echo 126 | ./4_Sources_126
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_127 && echo 127 | ./4_Sources_127
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_128 && echo 128 | ./4_Sources_128
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_129 && echo 129 | ./4_Sources_129
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_130 && echo 130 | ./4_Sources_130
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_131 && echo 131 | ./4_Sources_131
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_132 && echo 132 | ./4_Sources_132
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_133 && echo 133 | ./4_Sources_133
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_134 && echo 134 | ./4_Sources_134
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_135 && echo 135 | ./4_Sources_135
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_136 && echo 136 | ./4_Sources_136
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_137 && echo 137 | ./4_Sources_137
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_138 && echo 138 | ./4_Sources_138
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_139 && echo 139 | ./4_Sources_139
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_140 && echo 140 | ./4_Sources_140
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_141 && echo 141 | ./4_Sources_141
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_142 && echo 142 | ./4_Sources_142
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_143 && echo 143 | ./4_Sources_143
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_144 && echo 144 | ./4_Sources_144
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_145 && echo 145 | ./4_Sources_145
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_146 && echo 146 | ./4_Sources_146
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_147 && echo 147 | ./4_Sources_147
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_148 && echo 148 | ./4_Sources_148
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_149 && echo 149 | ./4_Sources_149
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_150 && echo 150 | ./4_Sources_150
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_151 && echo 151 | ./4_Sources_151
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_152 && echo 152 | ./4_Sources_152
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_153 && echo 153 | ./4_Sources_153
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_154 && echo 154 | ./4_Sources_154
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_155 && echo 155 | ./4_Sources_155
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_156 && echo 156 | ./4_Sources_156
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_157 && echo 157 | ./4_Sources_157
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_158 && echo 158 | ./4_Sources_158
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_159 && echo 159 | ./4_Sources_159
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_160 && echo 160 | ./4_Sources_160
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_161 && echo 161 | ./4_Sources_161
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_162 && echo 162 | ./4_Sources_162
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_163 && echo 163 | ./4_Sources_163
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_164 && echo 164 | ./4_Sources_164
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_165 && echo 165 | ./4_Sources_165
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_166 && echo 166 | ./4_Sources_166
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_167 && echo 167 | ./4_Sources_167
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_168 && echo 168 | ./4_Sources_168
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_169 && echo 169 | ./4_Sources_169
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_170 && echo 170 | ./4_Sources_170
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_171 && echo 171 | ./4_Sources_171
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_172 && echo 172 | ./4_Sources_172
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_173 && echo 173 | ./4_Sources_173
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_174 && echo 174 | ./4_Sources_174
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_175 && echo 175 | ./4_Sources_175
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_176 && echo 176 | ./4_Sources_176
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_177 && echo 177 | ./4_Sources_177
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_178 && echo 178 | ./4_Sources_178
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_179 && echo 179 | ./4_Sources_179
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_180 && echo 180 | ./4_Sources_180
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_181 && echo 181 | ./4_Sources_181
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_182 && echo 182 | ./4_Sources_182
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_183 && echo 183 | ./4_Sources_183
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_184 && echo 184 | ./4_Sources_184
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_185 && echo 185 | ./4_Sources_185
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_186 && echo 186 | ./4_Sources_186
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_187 && echo 187 | ./4_Sources_187
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_188 && echo 188 | ./4_Sources_188
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_189 && echo 189 | ./4_Sources_189
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_190 && echo 190 | ./4_Sources_190
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_191 && echo 191 | ./4_Sources_191
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_192 && echo 192 | ./4_Sources_192
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_193 && echo 193 | ./4_Sources_193
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_194 && echo 194 | ./4_Sources_194
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_195 && echo 195 | ./4_Sources_195
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_196 && echo 196 | ./4_Sources_196
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_197 && echo 197 | ./4_Sources_197
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_198 && echo 198 | ./4_Sources_198
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_199 && echo 199 | ./4_Sources_199
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_200 && echo 200 | ./4_Sources_200
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_201 && echo 201 | ./4_Sources_201
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_202 && echo 202 | ./4_Sources_202
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_203 && echo 203 | ./4_Sources_203
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_204 && echo 204 | ./4_Sources_204
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_205 && echo 205 | ./4_Sources_205
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_206 && echo 206 | ./4_Sources_206
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_207 && echo 207 | ./4_Sources_207
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_208 && echo 208 | ./4_Sources_208
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_209 && echo 209 | ./4_Sources_209
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_210 && echo 210 | ./4_Sources_210
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_211 && echo 211 | ./4_Sources_211
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_212 && echo 212 | ./4_Sources_212
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_213 && echo 213 | ./4_Sources_213
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_214 && echo 214 | ./4_Sources_214
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_215 && echo 215 | ./4_Sources_215
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_216 && echo 216 | ./4_Sources_216
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_217 && echo 217 | ./4_Sources_217
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_218 && echo 218 | ./4_Sources_218
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_219 && echo 219 | ./4_Sources_219
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_220 && echo 220 | ./4_Sources_220
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_221 && echo 221 | ./4_Sources_221
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_222 && echo 222 | ./4_Sources_222
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_223 && echo 223 | ./4_Sources_223
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_224 && echo 224 | ./4_Sources_224
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_225 && echo 225 | ./4_Sources_225
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_226 && echo 226 | ./4_Sources_226
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_227 && echo 227 | ./4_Sources_227
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_228 && echo 228 | ./4_Sources_228
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_229 && echo 229 | ./4_Sources_229
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_230 && echo 230 | ./4_Sources_230
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_231 && echo 231 | ./4_Sources_231
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_232 && echo 232 | ./4_Sources_232
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_233 && echo 233 | ./4_Sources_233
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_234 && echo 234 | ./4_Sources_234
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_235 && echo 235 | ./4_Sources_235
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_236 && echo 236 | ./4_Sources_236
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_237 && echo 237 | ./4_Sources_237
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_238 && echo 238 | ./4_Sources_238
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_239 && echo 239 | ./4_Sources_239
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_240 && echo 240 | ./4_Sources_240
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_241 && echo 241 | ./4_Sources_241
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_242 && echo 242 | ./4_Sources_242
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_243 && echo 243 | ./4_Sources_243
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_244 && echo 244 | ./4_Sources_244
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_245 && echo 245 | ./4_Sources_245
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_246 && echo 246 | ./4_Sources_246
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_247 && echo 247 | ./4_Sources_247
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_248 && echo 248 | ./4_Sources_248
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_249 && echo 249 | ./4_Sources_249
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_250 && echo 250 | ./4_Sources_250
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_251 && echo 251 | ./4_Sources_251
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_252 && echo 252 | ./4_Sources_252
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_253 && echo 253 | ./4_Sources_253
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_254 && echo 254 | ./4_Sources_254
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_255 && echo 255 | ./4_Sources_255
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_256 && echo 256 | ./4_Sources_256
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_257 && echo 257 | ./4_Sources_257
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_258 && echo 258 | ./4_Sources_258
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_259 && echo 259 | ./4_Sources_259
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_260 && echo 260 | ./4_Sources_260
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_261 && echo 261 | ./4_Sources_261
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_262 && echo 262 | ./4_Sources_262
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_263 && echo 263 | ./4_Sources_263
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_264 && echo 264 | ./4_Sources_264
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_265 && echo 265 | ./4_Sources_265
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_266 && echo 266 | ./4_Sources_266
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_267 && echo 267 | ./4_Sources_267
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_268 && echo 268 | ./4_Sources_268
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_269 && echo 269 | ./4_Sources_269
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_270 && echo 270 | ./4_Sources_270
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_271 && echo 271 | ./4_Sources_271
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_272 && echo 272 | ./4_Sources_272
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_273 && echo 273 | ./4_Sources_273
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_274 && echo 274 | ./4_Sources_274
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_275 && echo 275 | ./4_Sources_275
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_276 && echo 276 | ./4_Sources_276
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_277 && echo 277 | ./4_Sources_277
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_278 && echo 278 | ./4_Sources_278
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_279 && echo 279 | ./4_Sources_279
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_280 && echo 280 | ./4_Sources_280
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_281 && echo 281 | ./4_Sources_281
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_282 && echo 282 | ./4_Sources_282
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_283 && echo 283 | ./4_Sources_283
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_284 && echo 284 | ./4_Sources_284
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_285 && echo 285 | ./4_Sources_285
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_286 && echo 286 | ./4_Sources_286
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_287 && echo 287 | ./4_Sources_287
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_288 && echo 288 | ./4_Sources_288
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_289 && echo 289 | ./4_Sources_289
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_290 && echo 290 | ./4_Sources_290
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_291 && echo 291 | ./4_Sources_291
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_292 && echo 292 | ./4_Sources_292
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_293 && echo 293 | ./4_Sources_293
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_294 && echo 294 | ./4_Sources_294
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_295 && echo 295 | ./4_Sources_295
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_296 && echo 296 | ./4_Sources_296
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_297 && echo 297 | ./4_Sources_297
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_298 && echo 298 | ./4_Sources_298
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_299 && echo 299 | ./4_Sources_299
cd /home/onur/Desktop/Onur/Deltanu_constant/R_in_eq_R_Alfven && gfortran 4_Sources.f95 -o 4_Sources_300 && echo 300 | ./4_Sources_300
